"use client";

import React from "react";
import {
  Activity,
  Flame,
  CloudFog,
  Zap,
  Droplets,
  Thermometer,
  Layers,
  ArrowUpRight,
  TrendingUp,
  AlertCircle,
} from "lucide-react";
import { AirQualityData, PollutantDetail } from "@/lib/api";

interface PollutantGridProps {
  data: AirQualityData | null;
  loading: boolean;
}

interface PollutantConfig {
  key: string;
  name: string;
  chemical: string;
  description: string;
  safeLimit: number;
  icon: any;
  accent: string;
}

const POLLUTANTS_CONFIG: PollutantConfig[] = [
  {
    key: "pm25",
    name: "Fine Particulate Matter",
    chemical: "PM2.5",
    description: "Microscopic particles (≤2.5µm) capable of deep lung penetration.",
    safeLimit: 15.0,
    icon: CloudFog,
    accent: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
  },
  {
    key: "pm10",
    name: "Coarse Particulate Matter",
    chemical: "PM10",
    description: "Inhalable dust, pollen, and mold particles (≤10µm).",
    safeLimit: 45.0,
    icon: Layers,
    accent: "text-cyan-400 bg-cyan-500/10 border-cyan-500/20",
  },
  {
    key: "no2",
    name: "Nitrogen Dioxide",
    chemical: "NO₂",
    description: "Emissions primarily from combustion engines and power plants.",
    safeLimit: 25.0,
    icon: Flame,
    accent: "text-amber-400 bg-amber-500/10 border-amber-500/20",
  },
  {
    key: "o3",
    name: "Ground-Level Ozone",
    chemical: "O₃",
    description: "Secondary pollutant generated by sunlight reacting with smog.",
    safeLimit: 60.0,
    icon: Zap,
    accent: "text-purple-400 bg-purple-500/10 border-purple-500/20",
  },
  {
    key: "co",
    name: "Carbon Monoxide",
    chemical: "CO",
    description: "Colorless, odorless gas emitted by incomplete fuel burning.",
    safeLimit: 4.0,
    icon: Activity,
    accent: "text-rose-400 bg-rose-500/10 border-rose-500/20",
  },
  {
    key: "so2",
    name: "Sulfur Dioxide",
    chemical: "SO₂",
    description: "Toxic gas produced by burning fossil fuels containing sulfur.",
    safeLimit: 40.0,
    icon: AlertCircle,
    accent: "text-indigo-400 bg-indigo-500/10 border-indigo-500/20",
  },
];

export default function PollutantGrid({ data, loading }: PollutantGridProps) {
  if (loading || !data) {
    return (
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {[1, 2, 3, 4, 5, 6].map((i) => (
          <div key={i} className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 h-40 animate-pulse" />
        ))}
      </div>
    );
  }

  const pollutants = data.pollutants || {};

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-bold text-white tracking-tight flex items-center gap-2">
            <Layers className="w-4 h-4 text-emerald-400" />
            Pollutant Concentrations &amp; Breakdown
          </h3>
          <p className="text-xs text-slate-400 mt-0.5">
            Measured concentrations against World Health Organization (WHO) air quality guidelines.
          </p>
        </div>
        <span className="text-[11px] font-mono text-slate-400 bg-slate-900 px-2.5 py-1 rounded-lg border border-slate-800">
          Source: OpenAQ Sensors
        </span>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {POLLUTANTS_CONFIG.map((p) => {
          const detail: PollutantDetail | undefined = pollutants[p.key];
          const val = detail?.value ?? null;
          const unit = detail?.unit || "µg/m³";
          const Icon = p.icon;

          // Compute percentage relative to 3x safe limit for progress bar
          const maxScale = p.safeLimit * 3;
          const percentage = val !== null ? Math.min(100, Math.round((val / maxScale) * 100)) : 0;
          const isAboveSafe = val !== null && val > p.safeLimit;

          return (
            <div
              key={p.key}
              className="bg-slate-900/80 border border-slate-800 hover:border-slate-700/80 rounded-2xl p-5 shadow-sm transition-all flex flex-col justify-between"
            >
              {/* Top Header */}
              <div>
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <div className={`w-8 h-8 rounded-xl border flex items-center justify-center ${p.accent}`}>
                      <Icon className="w-4 h-4" />
                    </div>
                    <div>
                      <span className="font-bold text-white text-sm font-mono">{p.chemical}</span>
                      <p className="text-[10px] text-slate-400 truncate max-w-[130px]">{p.name}</p>
                    </div>
                  </div>

                  <span
                    className={`text-[10px] px-2 py-0.5 rounded-full border font-medium ${
                      val === null
                        ? "bg-slate-800 text-slate-400 border-slate-700"
                        : isAboveSafe
                        ? "bg-rose-500/10 text-rose-400 border-rose-500/20"
                        : "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                    }`}
                  >
                    {val === null ? "No Data" : isAboveSafe ? "Elevated" : "Within Limit"}
                  </span>
                </div>

                {/* Main Value */}
                <div className="my-2 flex items-baseline gap-2">
                  <span className="text-2xl font-bold font-mono text-white tracking-tight">
                    {val !== null ? val : "N/A"}
                  </span>
                  <span className="text-xs text-slate-400 font-mono">{unit}</span>
                </div>

                {/* Progress bar */}
                <div className="w-full bg-slate-950 rounded-full h-1.5 overflow-hidden my-2 border border-slate-800/80">
                  <div
                    className={`h-full rounded-full transition-all duration-500 ${
                      isAboveSafe ? "bg-rose-400" : "bg-emerald-400"
                    }`}
                    style={{ width: `${Math.max(5, percentage)}%` }}
                  />
                </div>
              </div>

              {/* Safe Guideline Note */}
              <div className="pt-2 border-t border-slate-800/60 flex items-center justify-between text-[10px] text-slate-500">
                <span>WHO Target: ≤{p.safeLimit}{unit}</span>
                <span className="text-slate-400">{val && val <= p.safeLimit ? "✓ Optimal" : "⚠ Exceeds"}</span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
